USE [Blissgig]
GO

/****** Object:  Table [dbo].[tbArticle]    Script Date: 07/13/2010 11:20:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[tbArticle](
	[Ident] [int] IDENTITY(1,1) NOT NULL,
	[Title] [varchar](100) NOT NULL,
	[Body] [text] NOT NULL,
	[CreateDate] [date] NOT NULL,
	[Hits] [int] NOT NULL,
 CONSTRAINT [PK_tbArticle] PRIMARY KEY CLUSTERED 
(
	[Ident] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

